version: 2.1

orbs:
  sonarqube: onehq/sonarqube@0.3.0
  
defaults: &defaults
  parameters:
    react-dist-tag:
      description: The dist-tag of react to be used
      type: string
      default: stable
  environment:
    # expose it globally otherwise we have to thread it from each job to the install command
    REACT_DIST_TAG: << parameters.react-dist-tag >>
  working_directory: /tmp/material-ui
  docker:
    - image: circleci/node:10
# CircleCI has disabled the cache across forks for security reasons.
# Following their official statement, it was a quick solution, they
# are working on providing this feature back with appropriate security measures.
# https://discuss.circleci.com/t/saving-cache-stopped-working-warning-skipping-this-step-disabled-in-configuration/24423/21
#
# restore_repo: &restore_repo
#   restore_cache:
#     key: v1-repo-{{ .Branch }}-{{ .Revision }}

commands:
  install_js:
    steps:
      - run:
          name: View install environment
          command: |
            node --version
            yarn --version
      - run:
          name: Resolve react version
          command: |
            node scripts/use-react-dist-tag
            # log a patch for maintainers who want to check out this change
            git --no-pager diff HEAD
      - restore_cache:
          keys:
            - v2-yarn-sha-{{ checksum "yarn.lock" }}
            - v2-yarn-sha-
      - run:
          name: Install js dependencies
          command: yarn
  prepare_chrome_headless:
    steps:
      - run:
          name: Install dependencies for Chrome Headless
          # From https://github.com/GoogleChrome/puppeteer/blob/811415bc8c47f7882375629b57b3fe186ad61ed4/docs/troubleshooting.md#chrome-headless-doesnt-launch
          command: |
            sudo apt-get update
            sudo apt-get install -y --force-yes gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
  setup-environment:
    description: "Setup requirements"
    steps:
      - run:
          name: "Setup environment"
          command: |
            apk update
            apk add --no-cache zip openjdk11-jre-headless

  install-engine:
    description: "Install Sonarqube scanner"
    parameters:
      engine_version:
        type: string
        default: "4.2.0.1873"
    steps:
      - run:
          name: "Install Sonarqube scanner"
          command: |
            echo "run install-engine"
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-<< parameters.engine_version >>.zip
            unzip sonar-scanner-cli-<< parameters.engine_version >>.zip
  code-analysis:
    description: "Run Sonarqube scanner for code analysis"
    parameters:
      organization:
        type: string
        default: "yfng96"
      host_url:
        type: string
        default: "http://sonarcloud.io"
      login:
        type: string
        default: "61e3ad26e9dcbb549871232ff5becff8fcfe5761"
      projectKey:
        type: string
        default: "material-ui"
      sources:
        type: string
        default: "./packages"
      github_oauth:
        type: string
        default: "0c77c0bc022608bd24d278380d03e79c7784e91c"
      github_repository:
        type: string
        default: "https://github.com/yfng96/material-ui"
      runner_opts:
        type: string
        default: "-Xms1024m -Xmx4096m"
      exclusions:
        type: string
        default: "**/test/*"
      engine_version:
        type: string
        default: "4.2.0.1873"
    steps:
      - run:
          name: "Code analysis"
          command: |
            export SONAR_RUNNER_OPTS="<< parameters.runner_opts >>"
            eval ./sonar-scanner-<< parameters.engine_version >>/bin/sonar-scanner \
              -Dsonar.host.url=<< parameters.host_url >> \
              -Dsonar.login=<< parameters.login >> \
              -Dsonar.projectKey=<< parameters.projectKey >> \
              -Dsonar.organization=<< parameters.organization >> \
              -Dsonar.sources=<< parameters.sources >> \
              -Dsonar.github.oauth=<< parameters.github_oauth >> \
              -Dsonar.github.repository=<< parameters.github_repository >> \
              -Dsonar.exclusions="<< parameters.exclusions >>"
  commit-analysis:
    description: "Run Sonarqube scanner for commit analysis"
    parameters:
      organization:
        type: string
        default: "yfng96"
      host_url:
        type: string
        default: "http://sonarcloud.io"
      login:
        type: string
        default: "61e3ad26e9dcbb549871232ff5becff8fcfe5761"
      projectKey:
        type: string
        default: "material-ui"
      projectVersion:
        type: string
        default: "1.0.0"
      sources:
        type: string
        default: "./packages"
      github_oauth:
        type: string
        default: "0c77c0bc022608bd24d278380d03e79c7784e91c"
      github_pullRequest:
        type: string
      github_repository:
        type: string
        default: "https://github.com/yfng96/material-ui"
      github_disableInlineComments:
        type: boolean
        default: false
      analysis_mode:
        type: string
        default: "preview"
      issuesReport_console_enable:
        type: boolean
        default: true
      runner_opts:
        type: string
        default: "-Xms1024m -Xmx4096m"
      exclusions:
        type: string
        default: "**/test/*"
      engine_version:
        type: string
        default: "4.2.0.1873"
    steps:
      - run:
          name: "Commit analysis"
          command: |
            echo "<< parameters.github_pullRequest >>"
            if [ ! -z "<< parameters.github_pullRequest >>" ]; then
              export SONAR_RUNNER_OPTS="<< parameters.runner_opts >>"
              eval ./sonar-scanner-<< parameters.engine_version >>/bin/sonar-scanner \
                -Dsonar.organization=<< parameters.organization >> \
                -Dsonar.host.url=<< parameters.host_url >> \
                -Dsonar.login=<< parameters.login >> \
                -Dsonar.projectKey=<< parameters.projectKey >> \
                -Dsonar.projectVersion=<< parameters.projectVersion >> \
                -Dsonar.issuesReport.console.enable=<< parameters.issuesReport_console_enable >> \
                -Dsonar.organization=<< parameters.organization >> \
                -Dsonar.sources=<< parameters.sources >> \
                -Dsonar.analysis.mode=<< parameters.analysis_mode >> \
                -Dsonar.github.pullRequest=<< parameters.github_pullRequest >> \
                -Dsonar.github.disableInlineComments=<< parameters.github_disableInlineComments >> \
                -Dsonar.github.oauth=<< parameters.github_oauth >> \
                -Dsonar.github.repository==<< parameters.github_repository >> \
                -Dsonar.exclusions="=<< parameters.exclusions >>"
            else
              echo "Check skipped..."
            fi
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - install_js
      - setup-environment
      - install-engine
      - run:
          name: Check for duplicated packages
          command: yarn deduplicate
      - save_cache:
          key: v2-yarn-sha-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/v4
  test_unit:
    <<: *defaults
    steps:
      - checkout
      - install_js
      - run:
          name: Tests fake browser
          command: yarn test:coverage
      - run:
          name: Check coverage generated
          command: |
            if ! [[ -s coverage/lcov.info ]]
            then
              exit 1
            fi
      - run:
          name: material-ui-icons
          command: |
            # latest commit
            LATEST_COMMIT=$(git rev-parse HEAD)

            # latest commit where packages/material-ui-icons was changed
            FOLDER_COMMIT=$(git log -1 --format=format:%H --full-diff packages/material-ui-icons)

            if [ $FOLDER_COMMIT = $LATEST_COMMIT ]; then
              echo "changes, let's run the tests"
              yarn workspace @material-ui/icons build:typings
              yarn workspace @material-ui/icons test:built-typings
            else
              echo "no changes"
            fi
      - run:
          name: typescript-to-proptypes
          command: |
            # latest commit
            LATEST_COMMIT=$(git rev-parse HEAD)

            # latest commit where packages/typescript-to-proptypes was changed
            FOLDER_COMMIT=$(git log -1 --format=format:%H --full-diff packages/typescript-to-proptypes)

            if [ $FOLDER_COMMIT = $LATEST_COMMIT ]; then
              echo "changes, let's run the tests"
              yarn workspace typescript-to-proptypes test
            else
              echo "no changes"
            fi
      - run:
          name: Coverage
          command: bash <(curl -s https://codecov.io/bash) -Z -C $CIRCLE_SHA1
  test_static:
    <<: *defaults
    steps:
      - checkout
      - install_js
      - run:
          name: '`yarn prettier` changes committed?'
          command: yarn prettier check-changed
      - run:
          name: Generate PropTypes
          command: yarn proptypes
      - run:
          name: Generate the documentation
          command: yarn docs:api
      - run:
          name: Generate the framer components
          command: yarn workspace framer build
      - run:
          name: Lint
          command: yarn lint:ci
      - run:
          name: Lint JSON
          command: yarn jsonlint
  test_types:
    <<: *defaults
    steps:
      - checkout
      - install_js
      - run:
          name: Transpile TypeScript demos
          command: yarn docs:typescript:formatted --disable-cache
      - run:
          name: Tests TypeScript definitions
          command: yarn typescript
  test_types_next:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Resolve typescript version
          environment:
            TYPESCRIPT_DIST_TAG: next
          command: |
            node scripts/use-typescript-dist-tag
            # log a patch for maintainers who want to check out this change
            git --no-pager diff HEAD
      - install_js
      - run:
          name: Tests TypeScript definitions
          command: |
            # ignore build failures
            # it's expected that typescript@next fails since the lines of the errors
            # change frequently. This build is monitored regardless of its status
            set +e
            # we want to see errors in all packages.
            # without --no-bail we only see at most a single failing package
            yarn typescript --no-bail
            exit 0
  test_browser:
    <<: *defaults
    steps:
      - checkout
      - install_js
      - prepare_chrome_headless
      - run:
          name: Tests real browsers
          command: yarn test:karma
      - store_artifacts:
          # hardcoded in karma-webpack
          path: /tmp/_karma_webpack_
          destination: artifact-file
      - run:
          name: Can we generate the @material-ui/core umd build?
          command: yarn workspace @material-ui/core build:umd
      - run:
          name: Test umd release
          command: yarn test:umd
workflows:
  version: 2
  pipeline:
    jobs:
      - checkout:
          filters:
            branches:
              ignore:
                - l10n
                - /dependabot\//
      - test_unit:
          requires:
            - checkout
      - test_static:
          requires:
            - checkout
      - test_types:
          requires:
            - checkout
      - test_browser:
          requires:
            - checkout
  react-next:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
                - next
    jobs:
      - test_unit:
          react-dist-tag: next
      - test_browser:
          react-dist-tag: next
  typescript-next:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
                - next
    jobs:
      - test_types_next
